# /.github/workflows/scrape_daily.yml
on:
  schedule:
    - cron: "0 12 * * *" # every day at 12am
  workflow_dispatch:

name: Daily Log Scrape
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Scrape all bosses
        run: python scrape.py update --from-latest --max-logs 10000 --patience 5
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
