# /.github/workflows/scrape_daily.yml
on:
  schedule:
    - cron: "0 12 * * *" # every day at 12am
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to push to the repository
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

name: Daily Log Scrape
jobs:
  scrape:
    name: Scrape latest logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip" # caching pip dependencies

      - run: pip install -r requirements.txt
      - name: Scrape all bosses
        run: python scrape.py update --from-latest --max-logs 10000 --patience 5

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update from latest logs"
